# run phpunit tests
name: PHPUnit Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest

    # phpunit tests process
    steps:
      # checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: curl, mbstring, intl

      # install dependencies
      - name: Install dependencies
        run: sh scripts/install.sh

      # run PHPUnit tests
      - name: Run PHPUnit tests
        run: php ./vendor/bin/phpunit
